Repository opensourceryclub/OpenSourcerySite, pull requests merged in 2020-10, with the labels that each got.

#20 Migrated from create-react-app to GatsbyJS
  .gitignore
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  gatsby-ssr.js
  jest.config.js
  package.json
  public/assets/stylesheets/base.css
  public/assets/stylesheets/index.css
  public/assets/stylesheets/projects.css
  public/index.html
  src/components/lib/Button.spec.tsx
  src/index.tsx
  src/layout/Layout.tsx
  src/pages/index.tsx
  src/react-app-env.d.ts
  yarn.lock
Labels: enhancement

#15 Added Github Actions
  .env
  .eslintrc.js
  .github/workflows/verify.yaml
  .gitignore
  package.json
  src/assets/serviceWorker.js
  src/components/Footer.tsx
  src/components/Main.tsx
  src/components/Nav.spec.tsx
  src/components/Nav.tsx
  src/components/lib/Button.spec.tsx
  src/components/lib/Button.tsx
  src/components/lib/Label.tsx
  src/components/lib/ProjectCard.tsx
  src/hooks/index.ts
  src/hooks/useAsync.ts
  src/hooks/useGithubRepos.ts
  src/hooks/util.ts
  src/layout/Layout.tsx
  src/pages/index.tsx
  src/react-app-env.d.ts
  yarn.lock
Labels: enhancement

#22 Devb
  src/assets/images/Badge.png
  src/assets/stylesheets/_header.scss
  src/components/Main.tsx
  src/components/Nav.tsx
  src/components/Projects.tsx
  src/components/lib/ProjectCard.tsx
  src/hooks/useGithubRepos.ts
  src/pages/projects.tsx
Labels: bug

#19 Fixed groupme icon
  public/assets/images/GroupMe.svg
  src/assets/images/GroupMe.svg
  src/assets/stylesheets/index.scss
  src/components/Main.tsx
  src/components/lib/Label.tsx
Labels: enhancement, good first issue, help wanted

#30 All kinds of layout improvements
  .eslintrc.js
  .github/workflows/verify.yaml
  .gitignore
  content/.keep
  gatsby-config.js
  package.json
  public/assets/images/Badge.png
  public/assets/images/Favicon.ico
  public/assets/scripts/index.js
  public/manifest.json
  src/assets/images/Favicon.ico
  src/assets/images/GroupMe.png
  src/assets/images/GroupMe.svg
  src/assets/scripts/index.js
  src/assets/style/index.css
  src/assets/stylesheets/index.scss
  src/components/Main.tsx
  src/components/Projects.tsx
  src/components/layout/Banner.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Grid.spec.tsx
  src/components/layout/Grid.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Nav.spec.tsx
  src/components/layout/Nav.tsx
  src/components/lib/Button.spec.tsx
  src/components/lib/Button.tsx
  src/components/lib/Label.tsx
  src/components/lib/ProjectCard.tsx
  src/hooks/useAsync.ts
  src/hooks/useBrand.ts
  src/hooks/useGithubRepos.ts
  src/hooks/useImages.ts
  src/pages/index.tsx
  src/pages/projects.tsx
  src/react-app-env.d.ts
  static/images/Badge.png
  static/images/Favicon.ico
  static/images/GroupMe.png
  static/images/GroupMe.svg
Labels: Major, enhancement
